[package]
name = "rudy-dev/random"

version = "1.0.0"

description = "Module for generating all types of data"

license = "MIT"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"